const amenitiesArr = [
  { title: "commercial, office", value: "commercial" },
  { title: "residential", value: "residential" },
  { title: "large table", value: "LargeTable" },
  { title: "medium table", value: "MediumTable" },
  { title: "small table", value: "SmallTable" },
  { title: "chairs", value: "Chairs" },
  { title: "wifi", value: "Wifi" },
  { title: "no wifi", value: "NoWifi" },
  { title: "ethernet", value: "Ethernet" },
  { title: "computer", value: "Computer" },
  { title: "mouse", value: "Mouse" },
  { title: "keyboard", value: "Keyboard" },
  { title: "printer", value: "Printer" },
  { title: "tv", value: "TV" },
  { title: "pen", value: "Pen" },
  { title: "paper", value: "Paper" },
  { title: "meeting room", value: "MeetingRoom" },
  { title: "headphone w. mic", value: "HeadphonewMic" },
  { title: "headphone", value: "Headphone" },
  { title: "coffee", value: "Coffee" },
  { title: "couch", value: "Couch" },
  { title: "outdoor deck", value: "OutDoorDeck" },
  { title: "penthouse", value: "Penthouse" },
  { title: "outlet", value: "Outlet" },
  { title: "wheelchair", value: "WheelChair" },
  { title: "no wheelchair", value: "NoWheelChair" },
  { title: "gym", value: "Gym" },
  { title: "frontyard", value: "FrontYard" },
  { title: "water", value: "Water" },
  { title: "swimming pool", value: "SwimmingPool" },
  { title: "billiard", value: "Billiard" },
  { title: "ping pong", value: "PingPong" },
];
export { amenitiesArr };
